project_id = "xoipyycgycmpflfnrlty"

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true

[functions.analyze-image]
verify_jwt = true

[functions.find-diagram]
verify_jwt = true
